style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/ik-performance/performance-blueprint-project.git
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject