name: pre-commit-validate
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  validation:
    name: pre-commit-validate
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '1'
      - name: Install Deps
        run: |
          brew install pre-commit shellcheck
      - name: Check All Files
        run: |
          pre-commit run --all-files
